default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tweeter_development
test:
  <<: *default
  database: tweeter_test
production:
  <<: *default
  database: tweeter_production
