# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19271a1c47528527e67ba8dbe408eeb08df8b0b4f3e20c847661da4b5b99e5160913a86829eb035c4b12ee34960de59378050dd23ea74ae0e023f43ed3093086
  consumer_key: ckVNlB3tHD14h4TIPkNt70o83
  consumer_secret: ayZVzYRqPGOvev9G4kNkn2zY5I0TnKJIEw1lY8D8JvRjk8D8xr
  access_token: 98751863-Wr7SpAgXnNs94DIxMa4UPRU5N4RnU7TcUqCfUiHP0
  access_token_secret: HfrSADZZtCVJ51rFxaXzRVddS0kPZ7JGZT41q5TE5Rzdy


test:
  secret_key_base: 43fabe2722406a1c91d648b4241acf279c2aefb73bb61b38f5be4c854a3cd2ca4176e726e77b6f0fc2f9226ce0ae809fa14438507fabee7d6d6027349e6c56e1
  consumer_key: ckVNlB3tHD14h4TIPkNt70o83
  consumer_secret: ayZVzYRqPGOvev9G4kNkn2zY5I0TnKJIEw1lY8D8JvRjk8D8xr
  access_token: 98751863-Wr7SpAgXnNs94DIxMa4UPRU5N4RnU7TcUqCfUiHP0
  access_token_secret: HfrSADZZtCVJ51rFxaXzRVddS0kPZ7JGZT41q5TE5Rzdy

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 415dfd63a38af0592b837445d37d6b44d4023bf53d9372a6917f2ca8d0912529985001a0227751187cb4e5e083231c5e9ad0c8748fa3c0235258c54927f81988
  consumer_key: ckVNlB3tHD14h4TIPkNt70o83
  consumer_secret: ayZVzYRqPGOvev9G4kNkn2zY5I0TnKJIEw1lY8D8JvRjk8D8xr
  access_token: 98751863-Wr7SpAgXnNs94DIxMa4UPRU5N4RnU7TcUqCfUiHP0
  access_token_secret: HfrSADZZtCVJ51rFxaXzRVddS0kPZ7JGZT41q5TE5Rzdy

  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # consumer_key: <%= ENV["CONSUMER_KEY"] %>
  # consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
  # access_token: <%= ENV["ACCESS_TOKEN"] %>
  # access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"] %>
